#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

ufw allow 1344
apt-get -y update
apt-get install -y haproxy

printf %s " 	42026-web-02	ubuntu	52.73.23.55
backend web-backend
        balance roundrobin
        option forwardfor
        server 42026-web-01 3.238.236.255:80 check
        server 42026-web-02 52.73.23.55:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
